{velor2=velor3, кроме порядка w,v в параметрах}

PROCEDURE  VELOR3(X,Y,Z,VX,VY,VZ: EXTENDED;
                  VAR A,E,I,OM,W,v: EXTENDED;MU: EXTENDED);
VAR    B1,R1,R2,R3,RR,R,VV1,VV,P,P1,YZ,XZ,XY,U: EXTENDED;
BEGIN
R2:=X*X+Y*Y+Z*Z;
R:=SQRT(R2);
RR:=X*VX+Y*VY+Z*VZ;
VV1:=VX*VX+VY*VY+VZ*VZ;VV:=SQRT(VV1);
B1:=SQRT(MU);
A:=R/(2-R*VV1/MU);
E:=1-(R2*VV1-RR*RR)/(A*MU);
P:=A*(1-E);P1:=SQRT(P);
E:=SQRT(E);
YZ:=Y*VZ-Z*VY;
XZ:=X*VZ-Z*VX;
XY:=X*VY-Y*VX;
I:=ARCTAN(SQRT(YZ*YZ+XZ*XZ)/XY);
IF XY<0 THEN  I:=PI+I;
OM:=ARCTAN(YZ/XZ);
IF  XZ<0 THEN  OM:=PI+OM;
R1:=P-R;
V:=ARCTAN(P1*RR/(B1*R1));
IF R1<0 THEN  V:=PI+V;
R3:=R2*VZ-RR*Z;
U:=ARCTAN(Z*P1*B1/R3);
IF  R3<0 THEN  U:=PI+U;
W:=U-V; IF W<0 THEN  W:=2*PI+W;
END; (*VELOR2*)